# Site Meta Information
title: Slow Grub
description: An app to help you cut your food's impact on climate
url: "http://www.slowgrub.com"  # Base hostname & protocol for the site
baseurl: ""  # Subpath of your site, e.g., /blog
theme: minima  # Assuming you are using the default minima theme

# Build Configuration
markdown: kramdown
plugins:
  - jekyll-feed

# Navigation Bar
# List of items to be displayed on the navbar
nav:
  - title: "ğŸŒ± App Look"
    url: "#app-look"
  - title: "ğŸŒ± Join Us"
    url: "#get-involved"
  - title: "ğŸŒ± Problems We Solve"
    url: "#problems"
  - title: "ğŸŒ± Achievements"
    url: "#achievements"
  - title: "ğŸŒ± Meet the Team"
    url: "#team"
  - title: "ğŸ“– Blog"
    url: "blogs.html"
  - title: "ğŸ–¼ï¸ Gallery"
    url: "/gallery.html"

# Add any other configurations below as needed
